project:
  type: book
  output-dir: docs

book:
  title: "PrWR 3cH (Schuljahr 2025/2026)"
  author: "Jacques Mock Schindler"
  date: today
  chapters:
    - index.qmd
    - part: "Unternehmensprojekt"
      chapters:
        - files/einfuehrung.qmd
        - files/auftrag.qmd
        - files/beurteilung.qmd
        - files/anleitung.qmd
  repo-url: https://github.com/SkriptenMk/PRWR_cH_23-27
  repo-actions: [issue]

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    pdf-engine: lualatex
    documentclass: scrreprt
    papersize: a4
    lang: de-CH
    toc: true
    number-sections: true
    colorlinks: true